language: ruby
dist: xenial
cache: bundler

script: bundle exec rspec

matrix:
  include:
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 2.7
    - rvm: 2.6
      env: COVERAGE=Summary,Coveralls
    - rvm: 2.7
    - rvm: truffleruby
    - rvm: jruby-head
      env: JRUBY_OPTS="--debug -X+O"
    - rvm: ruby-head
    - rvm: 2.6
      os: osx
  allow_failures:
    - rvm: truffleruby
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: truffleruby
