language: ruby
sudo: false
dist: trusty
cache: bundler

before_script:
  - gem update --system
  - gem install bundler

rvm:
  - 2.4
  - 2.5
  - 2.6
  - jruby-head
  - ruby-head
  - rbx-3
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-3
